name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: (Client) Grant execute permission for gradlew
      working-directory: TP1/Client
      run: chmod +x gradlew
    - name: (Serveur) Grant execute permission for gradlew
      working-directory: TP1/Serveur
      run: chmod +x gradlew
    - name: (Client) Build
      working-directory: TP1/Client
      run: ./gradlew build
    - name: (Serveur) Build
      working-directory: TP1/Serveur
      run: ./gradlew build
    - name: (Client) Run tests
      working-directory: TP1/Client
      run: ./gradlew test
    - name: (Serveur) Run tests
      working-directory: TP1/Serveur
      run: ./gradlew test
